variables:
    PYHTON_MODULE: 'rw'


.test_template: &test_def
  script:
  - pip install pytest pytest-cov
  - pip install -e .
  - py.test --cov ${PYTHON_MODULE} --cov doc --cov test


cache:
  untracked: false
  key: pip-cache
  paths:
    - ~/.cache/pip


python3.5:
  <<: *test_def
  image: python:3.5


python3.6:
  <<: *test_def
  image: python:3.6


python3.7:
  <<: *test_def
  image: python:3.7


pep8:
  image: python:3.7
  script:
    - pip install pycodestyle
    - pip install -e .
    - pycodestyle ${PYTHON_MODULE}
