
python2.7:
  image: python:2.7
  script:
  - pip install tox coveralls pytest-cov pep8
  # run tests in different python versions with tox
  # and run pep8
  - python setup.py test
  # for coverage
  - pip install -e .
  - py.test --cov rw --cov doc --cov test


python3.5:
  image: python:3.5
  script:
  - pip install tox coveralls pytest-cov pep8
  # run tests in different python versions with tox
  # and run pep8
  - python setup.py test
  # for coverage
  - pip install -e .
  - py.test --cov rw --cov doc --cov test
